//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaTestProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sonuc
    {
        public int Sonuc_ID { get; set; }
        public string Sonuc { get; set; }
    }
}
