//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaTestProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Test
    {
        public int Test_ID { get; set; }
        public string UygulamaAdi { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
        public Nullable<System.DateTime> Test_Tarihi { get; set; }
        public string Test_Detay { get; set; }
        public Nullable<int> Sonuc_ID { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
    }
}
